---
- name: Download and extract Julia
  unarchive:
    src: "https://julialang-s3.julialang.org/bin/linux/x64/{{ julia_version | regex_replace('^([0-9])\\.([0-9]*).*', '\\1.\\2') }}/julia-{{ julia_version }}-linux-x86_64.tar.gz"
    dest: /opt
    remote_src: yes

- name: Create a symbolic link
  file:
    src: "/opt/julia-{{ julia_version }}"
    dest: /opt/julia-latest
    state: link
