---

- name: Perform a full upgrade
  apt:
    upgrade: dist
    update_cache: yes
    lock_timeout: 600
    dpkg_options: 'force-confold,force-confdef'
  when: nectar_test_build is not defined

- name: Install extra packages
  package:
    name: "{{ install_packages | default([]) + extra_packages | default([]) }}"
    update_cache: yes
    state: latest
