---
- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}_{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- name: install extra packages
  package:
    name: "{{ extra_packages }}"
    state: present
  when: extra_packages is defined

- name: remove unnecessary packages
  package:
    name: "{{ remove_packages }}"
    state: absent
  when: remove_packages is defined
