---
- name: install Fedora Scientific packages
  become: yes
  dnf:
    name: "{{ fedora_scientific_packages }}"
    exclude: "{{ fedora_scientific_packages_exclude }}"
    state: present

- name: disable kde lockscreen
  copy:
    src: kscreenlockerrc
    dest: /etc/xdg/

- name: enable wheel group permissions for polkit
  copy:
    src: 49-nopasswd_global.rules
    dest: /etc/polkit-1/rules.d/49-nopasswd_global.rules
