---
- name: install Fedora Scientific packages
  dnf:
    name: "{{ fedora_scientific_packages }}"
    exclude: "{{ fedora_scientific_packages_exclude }}"
    state: present

- name: disable kde lockscreen
  copy:
    src: kscreenlockerrc
    dest: /etc/xdg/

- name: enable wheel group permissions for polkit
  copy:
    src: 49-nopasswd_global.rules
    dest: /etc/polkit-1/rules.d/49-nopasswd_global.rules

- name: Disable suspend and hibernation
  ansible.builtin.systemd:
    name: "{{ item }}"
    masked: yes
  with_items:
    - sleep.target
    - suspend.target
    - hibernate.target
    - hybrid-sleep.target
