---
- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}_{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

# Add the https://launchpad.net/~johnmullen/+archive/ubuntu/xrdp PPA for newer XRDP
# as 0.9.12 has broken RDP drive support
- name: Add XRDP PPA for Ubuntu
  apt_repository:
    repo: 'ppa:johnmullen/xrdp'
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Install XRDP
  package:
    name: '{{ xrdp_packages }}'
    state: present

- name: Add XRDP PPA for Ubuntu
  apt_repository:
    repo: 'ppa:johnmullen/xrdp'
    state: absent
  when: ansible_distribution == 'Ubuntu'

# Without this, TLS negotiation fails as the XRDP user is unable to read
# the self-signed cert/key
- name: Adding xrdp user to the ssl-cert group
  user:
    name: xrdp
    groups: ssl-cert
    append: yes
  when: ansible_distribution == 'Ubuntu'

- name: Allow non-root users to login with xwrapper
  shell: 'echo "xserver-xorg-legacy xserver-xorg-legacy/xwrapper/allowed_users select Anybody" | debconf-set-selections'
  when: ansible_distribution == 'Ubuntu'

- name: Create xrdp-pulseaudio-installer directory
  file:
    path: /var/lib/xrdp-pulseaudio-installer
    state: directory
  when: ansible_distribution == 'Ubuntu'

# To build, follow the instructions from
#  https://github.com/neutrinolabs/pulseaudio-module-xrdp/wiki/README
- name: Install XRDP PulseAudio modules
  copy:
    src: "xrdp-pulseaudio/{{ ansible_distribution_release }}/{{ item }}"
    dest: "/var/lib/xrdp-pulseaudio-installer/{{ item }}"
  with_items:
    - module-xrdp-sink.so
    - module-xrdp-source.so
  when: ansible_distribution == 'Ubuntu'

- name: Start XRDP
  service:
    name: xrdp
    enabled: yes
    state: started
