---
- name: Add cloud repository for CentOS
  yum_repository:
    name: "CentOS-OpenStack-{{ openstack_clients_version }}"
    description: "CentOS-$releasever - OpenStack"
    baseurl: "http://mirror.centos.org/centos/{{ ansible_distribution_major_version }}/cloud/x86_64/openstack-{{ openstack_clients_version }}/"
    gpgcheck: no

- name: Install OpenStack client packages
  yum:
    name: "{{ openstack_clients_packages }}"
    state: present
