---
rstudio_dependencies: []

# Valid choices are centos7, rhel8, rhel9
rstudio_distro: "{% if ansible_distribution_major_version|int < 8 %}centos7{% else %}rhel{{ ansible_distribution_major_version }}{% endif %}"
rstudio_package_url: "https://download1.rstudio.org/electron/{{ rstudio_distro }}/x86_64/rstudio-{{ rstudio_version }}-x86_64.rpm"
