---
rstudio_dependencies:
  - libxkbcommon-x11-0  # core dumped without it

# Yes, we use Bionic even for Focal
rstudio_distro: "{% if ansible_distribution_major_version|int < 22 %}bionic{% else %}jammy{% endif %}"
rstudio_package_url: "https://download1.rstudio.org/electron/{{ rstudio_distro }}/amd64/rstudio-{{ rstudio_version }}-amd64.deb"
