---
- hosts: all
  become: yes
  gather_facts: yes

  vars_files:
    - vars/main.yml
    - vars/fedora-scientific.yml

  roles:
    - image-name
    - default-user
    - setup
    - fedora-scientific
    - common
    - xrdp
    - config
    - testing
    - nectar-user
    - facts
    - cleanup
