---
- hosts: all
  become: yes
  gather_facts: yes

  vars_files:
    - vars/main.yml
    - vars/neurodesk.yml

  roles:
    - image-name
    - default-user
    - setup
    - lxde-desktop
    - cvmfs
    - singularity
    - neurodesk
    - vscode
    - common
    - xrdp
    - config
    - testing
    - nectar-user
    - facts
    - cleanup
