---
- hosts: all
  become: yes
  gather_facts: yes

  vars_files:
    - vars/main.yml

  roles:
    - image-name
    - default-user
    - setup
    - xfce4-desktop
#    - mate-desktop
#    - owncloud-client
#    - x2go-server
    - xrdp
    - config
    - testing
    - facts
    - cleanup
