---
- hosts: all
  become: yes
  gather_facts: yes

  vars_files:
    - vars/main.yml
    - vars/geodesktop.yml

  roles:
    - image-name
    - default-user
    - setup
    - xfce4-desktop
    - xrdp
    - common
    - pgadmin
    - anaconda
    - r
    - r-studio
    - owncloud-client
    - config
    - testing
    - nectar-user
    - facts
    - cleanup
