---
- hosts: all
  become: yes
  gather_facts: yes

  vars_files:
    - vars/main.yml

  roles:
    - image-name
    - default-user
    - setup
    - mate-desktop
#    - owncloud-client
    - xrdp
    - config
    - testing
    - facts
    - cleanup
