---
- name: Set Mate as default desktop on CentOS 7
  copy:
    dest: /etc/sysconfig/desktop
    content: 'PREFERRED=mate-session'
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 7
